### ISSUE TITLE
Discourage monadic use of Cell

### ISSUE THREAD

**Issue by clinuxrulz** [SodiumFRP/purescript-sodium#20]
I'd recommend removing the Monad instance for Cell and just go up to Applicative instead.

If a newbie come along and used the monadic interface heavily (E.g. do-notation), then he/she could run into performance problems as almost all their sodium objects would be connected with ```switchC```, and each time the cell changes within a ```switchC``` there is a rank re-sort happening.

**Comment by dakom** [comment]
Hmmm... good point! I see in Reactive Banana they encountered a similar issue and opted to provide a totally different type of monad (and also no switchC alternative): https://github.com/HeinrichApfelmus/reactive-banana/issues/121#issuecomment-392284233

Since we do have `switchC` though - how about a big warning on the main Readme (covering both switch _and_ bind) as well as documentation on the monad instance?

**Comment by clinuxrulz** [comment]
Their ```Moment``` monad is the transaction monad. At the end of its execution, its an automatic end of transaction. Its really to tidy up transactions.

We really want to discourage this:
```
let cc = (do
        a <- ca
        b <- cb
        return a + b
    )
```

And encourage this:
```
let cc = (_ + _) <$> ca <*> cb
```

**Comment by dakom** [comment]
Oh wow... interesting! Does that apply to switchS too, i.e. both of those should return an `Effect` ?

**Comment by clinuxrulz** [comment]
```switchS``` is pure

**Comment by clinuxrulz** [comment]
in that pdf, anything with ```T ->``` in it is a side effect.

**Comment by dakom** [comment]
Just to understand better - can you confirm if this is all correct?

`Value`, `Hold`, `SwitchC`, and `Sample` all are side effects because if they are called at different times, they may yield values that are _not_ referentially transparent.

Specifically:

1. Value called before or after a Cell has changed, will give a Stream of different Events
2. Hold called before or after a stream has fired, will give a Cell which has different values
3. SwitchC called before or after either Cell has changed, will give a Cell of a different value
4. Sample called when a Cell has changed, will give a different result

Here is a small typescript example showing this with SwitchC:

```
const cInner = new CellSink('a');
const cOuter = new CellSink(cInner);

const cFlat1 = Cell.switchC(cOuter);

cFlat1.listen(x => console.log(`flat1: ${x}`));

setTimeout(() => {
  cInner.send('b');
  const cFlat2 = Cell.switchC(cOuter);
  cFlat2.listen(x => console.log(`flat2: ${x}`));
})

/*
Results: 

flat1: a
flat1: b
flat2: b
*/
```

**Comment by the-real-blackh** [comment]
Yes, cell doesn't form a monad. One of my concerns is to make Sodium friendly to people who don't understand functional programming. So in certain contexts that might be an argument in favour of Moment being a monad.

I'm not saying it should or shouldn't. I just want Sodium to be as good as it can be. I don't have any desire to be in control. You're doing great work, guys!

**Comment by dakom** [comment]
Cool :) I'm working on a PR to implement all these changes, will be done soon hopefully...

**Comment by dakom** [comment]
Here's the PR: https://github.com/SodiumFRP/purescript-sodium/pull/21

**Comment by dakom** [comment]
Fixed in https://github.com/SodiumFRP/purescript-sodium/issues/12
